package eu.yozozchomutova;

import sun.awt.image.ToolkitImage;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;

public enum ProducingUnit {
    ANTIAIR1((byte) 0x01, "Antiair 1", "ant1"),
    ANTIAIR2((byte) 0x02, "Antiair 2", "ant2"),
    ANTIAIR3((byte) 0x03, "Antiair 3", "ant3"),

    ARTILLERY1((byte) 0x04, "Artillery 1", "art1"),
    ARTILLERY2((byte) 0x05, "Artillery 2", "art2"),
    ARTILLERY3((byte) 0x06, "Artillery 3", "art3"),

    TANK1((byte) 0x07, "Tank 1", "tank1"),
    TANK2((byte) 0x08, "Tank 2", "tank2"),
    TANK3((byte) 0x09, "Tank 3", "tank3"),

    FLAME1((byte) 0x0A, "Flame 1", "flame1"),
    FLAME2((byte) 0x0B, "Flame 2", "flame2"),
    FLAME3((byte) 0x0C, "Flame 3", "flame3"),

    SPECIAL1((byte) 0x0D, "Special 1", "spec1"),
    SPECIAL2((byte) 0x0E, "Special 2", "spec2"),
    SPECIAL3((byte) 0x0F, "Special 3", "spec3"),

    GOLD1((byte) 0x10, "Gold 1", "gold1"),
    GOLD2((byte) 0x11, "Gold 2", "gold2"),
    GOLD3((byte) 0x12, "Gold 3", "gold3"),

    RESEARCH1((byte) 0x13, "Research 3", "res1"),
    RESEARCH2((byte) 0x14, "Research 2", "res2"),
    RESEARCH3((byte) 0x15, "Research 3", "res3"),

    ENERGY1((byte) 0x16, "Energy 1", "en1"),
    ENERGY2((byte) 0x17, "Energy 2", "en2"),
    ENERGY3((byte) 0x18, "Energy 3", "en3"),

    BOMBER((byte) 0x1E, "Bomber", "bomber"),
    CARRIER((byte) 0x1F, "Carrier", "carryall"),
    FIGHTER((byte) 0x20, "Fighter", "fighter"),
    TRIPLER((byte) 0x21, "Tripler", "tripler"),
    METEORITES((byte) 0x22, "Meteorites", "meteor"),

    KODIAK_R((byte) 0x29, "Kodiak", "kodiak"),
    ANTIAIR_R((byte) 0x2A, "Antiair", "antiair_robot"),
    JAGUAR_R((byte) 0x2B, "Jaguar", "jaguar"),
    ROTARY_R((byte) 0x2C, "Rotary", "rotary"),
    ACHILLES_R((byte) 0x2D, "Achilles", "achilles"),
    NAB((byte) 0x2E, "NAB", "nab"),
    ;

    public byte id;

    public String name;

    //Autogenerated
    public int width;
    public int height;
    public int[] iconPixels;

    ProducingUnit(byte id, String name, String iconPath) {
        this.id = id;
        this.name = name;

        try {
            //Blue
            Image iconImg = ImageIO.read(new File("src/ui/" + iconPath + ".png")).getScaledInstance(32, 32, Image.SCALE_FAST);

            //Image to BufferedImage
            BufferedImage icon = new BufferedImage(iconImg.getWidth(null),iconImg.getHeight(null),BufferedImage.TYPE_INT_ARGB);
            Graphics bg = icon.getGraphics();
            bg.drawImage(iconImg, 0, 0, null);
            bg.dispose();

            this.width = icon.getWidth();
            this.height = icon.getHeight();

            iconPixels = icon.getRGB(0, 0, width, height, null, 0, width);
        } catch (Exception io) {
            io.printStackTrace();
        }
    }

    public static ProducingUnit getPUnitType(byte pUnitByte) {
        ProducingUnit[] pUnitTypes = ProducingUnit.values();

        for (int i = 0; i < pUnitTypes.length; i++) {
            if (pUnitTypes[i].id == pUnitByte)
                return pUnitTypes[i];
        } return null;
    }
}
